version: '3.8'

networks:
  vue:

services:
  vue-ui:
    build:
      context: ./vue-app
    ports:
      - "8080:8080"
    stdin_open: true
    volumes:
      - './vue-app:/app'
    networks:
      - vue
    depends_on:
      - npm

  npm:
    image: node:current-alpine 
    volumes:
      - ./vue-app:/app
    working_dir: /app
    entrypoint: [ 'npm' ]
    command: [ 'install' ]

